[project]
name = "flashcards"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "openpyxl>=3.1.2"
]


# Specify the package builder
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Tell Hatchling to include the package_1 folder as a package
[tool.hatch.build]
include = ["packages/flashcards"]

# manage the environment like a package rather than a standalone virtual environment
[tool.uv]
package = true
